language: ruby
rvm:
  - 2.2
install:
  - nvm install v5.0.0
  - npm install
before_script:
  - gem install awesome_bot
  - npm install -g gulp-cli
script:
  - awesome_bot README.md --allow-dupe
  - gulp test
